### ISSUE TITLE
Interested in contributing

### ISSUE THREAD

**Issue by ngortheone** [aaschmid/taskwarrior-java-client#1]
@aaschmid Hi!

I have faced the same problem as you and event started writing something similar. And then found this repo!

What is the current status of the project? I have some enthusiasm and time to help improve it!

**Comment by aaschmid** [comment]
@ngortheone thanks for your request. 
The status is that IMO this little library is stable and working. 

Depending on what features you are missing, we can come up with a solution and a way of work. So what features would you like to see?

**Comment by ngortheone** [comment]
@aaschmid Thanks for fast reply!

As of now there are no specific asks. I forked https://github.com/kvj/TaskwarriorAndroid and tried to improve it in number of ways:

@kvj forked taskwarrior and removed GNUTLS support, to avoid compiling it. So I fixed that, got a working build of gmp, gnutls, nettle, util-linux and taswarrior itself by android toolchain for 4 main ABIs..
Then I started replacing usage of the binary to  JNI call to taskwarrior.
(https://github.com/ngortheone/taskwarrior-android/tree/master/contrib)

The problem is that taskwarrior binary is not really a library, it just dumps everything to stdout, and it is not written in a way that makes using it externally easy. So the amount of JNI code became non-trivial and I started disliking the idea.

This is where I started thinking about java/kotlin taskd client. So the next step would be to try using your lib in taskwarrior-android.

BTW, what do you use on mobile?

**Comment by aaschmid** [comment]
Sounds reasonable. I do using https://github.com/tasks/tasks (forked from Astrid as Yahoo stop developing it). I wanted to integrate a taskwarrior sync which I got working as PoC but unfortunately taskwarriors recurring features are incompatible (e.g. 1m = 30d in taskwarrior) which made a generic approach not that easy. As I could not spent that much time anyways, I kind of stopped making it production ready that time.

Note: It was just running as PoC in Android Studio on the simulator and nowadays there are a lot of conflicts because the tasks developer restructured the internals of tasks such that I was not quickly able to rebase my commits some month ago ...

**Comment by aaschmid** [comment]
I will close this, if you are fine with it @ngortheone?
